# Project information
site_name: "Grupo 07 - NLP"
site_description: ""
site_author: "Grupo 07 - NLP"
site_url: "https://ResidenciaTICBrisa.github.io/07_ProcessamentoLinguagemNatural/"

# Repository
repo_name: "NLP - 07"
repo_url: "https://github.com/ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural"

# Copyright
copyright: "Copyright &copy; 2023 Grupo 07 - NLP"
theme:
  logo: "assets/img/logo.png"
  favicon: "assets/img/logo.png"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
  language: "pt"
  name: "material"
  palette:
    primary: "blue"
    accent: "grey"

# Content Menu
nav:
  - Index: "index.md"
  - Gerência:
    - Plano metodológico: "management/metodologia.md"
    - Plano de Comunicação: "management/comunicacao.md"
    - Definição de papeis: "management/papeis.md"
  - Projeto:
    - Código de conduta: "project/CODE_OF_CONDUCT.md"
  - Processo de desenvolvimento: "processo_de_desenvolvimento.ipynb"

# Plugin jupyter
plugins:
  - mkdocs-jupyter