# Project information
site_name: "Grupo 07 - NLP"
site_url: "https://ResidenciaTICBrisa.github.io/07_ProcessamentoLinguagemNatural/"

# Repository
repo_name: "NLP - 07"
repo_url: "https://github.com/ResidenciaTICBrisa/07_ProcessamentoLinguagemNatural"

copyright: "Copyright &copy; 2023 Grupo 07 - NLP"

theme:
  logo: "assets/img/logo.png"
  favicon: "assets/img/logo.png"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - navigation.tabs
  language: "pt"
  name: "material"
  palette:
    primary: "blue"
    accent: "grey"

# Content Menu
nav:
  - Home: "index.md"
  - Gerência:
    - Plano metodológico: "management/metodologia.md"
    - Plano de Comunicação: "management/comunicacao.md"
    - Definição de papeis: "management/papeis.md"
  - Projeto:
    - Código de conduta: "project/CODE_OF_CONDUCT.md"
  - Processo de desenvolvimento: "processo_de_desenvolvimento.ipynb"
  - Registro de atividades: "atividade.md"

# Plugin jupyter
plugins:
  - mkdocs-jupyter
  - search:
      lang:
        - pt
        - en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
